var CELL_SIZE = 40;
var CELLS_WIDE = 10;
var CELLS_HEIGH = 20;

var CANVAS_WIDTH = CELL_SIZE * CELLS_WIDE;
var CANVAS_HEIGHT = CELL_SIZE * CELLS_HEIGH;

var ICOLOR = "#ED1C24";
var JCOLOR = "#EEEE00";
var LCOLOR = "#CA157B";
var OCOLOR = "#3347FF";
var SCOLOR = "#00EEEE";
var TCOLOR = "#32CD32";
var ZCOLOR = "#FF7F00";
